Modify CD file

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -26,27 +26,20 @@ jobs:
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            cd ~/frappe_docker
-            docker exec frappe_docker-backend-1 /bin/bash -c "
-              cd apps/managefarmspro/ &&
-              git pull origin staging &&
-              bench --site frontend migrate &&
-              exit
-            "
-            docker stop frappe_docker-frontend-1 frappe_docker-redis-queue-1 frappe_docker-redis-cache-1 frappe_docker-queue-short-1 frappe_docker-db-1 frappe_docker-scheduler-1 frappe_docker-queue-long-1 frappe_docker-websocket-1 frappe_docker-backend-1
-            sleep 60
-            docker start frappe_docker-frontend-1 frappe_docker-redis-queue-1 frappe_docker-redis-cache-1 frappe_docker-queue-short-1 frappe_docker-db-1 frappe_docker-scheduler-1 frappe_docker-queue-long-1 frappe_docker-websocket-1 frappe_docker-backend-1
-            sleep 60
-
-      - name: Check deployment status
-        run: |
-          for i in {1..10}; do
+            cd staging/frappe_docker/
+            docker compose -f pwd.yml down
+            sleep 120
+            docker compose -f pwd.yml up -d
+            sleep 120
             if curl -s -o /dev/null -w "%{http_code}" https://khasihan.xyz | grep 200; then
               echo "Deployment successful!"
-              exit 0
+            else
+              echo "Deployment failed"
+              exit 1
             fi
-            sleep 10
-          done
-          echo "Deployment failed"
-          exit 1
+            exit
+
+      - name: Finish CD
+        if: success()
+        run: echo "CD process completed."
 
